version: '1.0'
services:
  node-loja:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-loja
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true # Para permitir a interação (equivalente ao -it)
    tty: true        # Necessário para permitir interação no terminal
    command: npm run start:dev # Comando que será executado no container (ajuste conforme sua necessidade)
